version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
    - ineffassign
    - gosec

  settings:
    errcheck:
      check-blank: false

    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unexported-return
          disabled: true